branches:
  - main
preset: "angular"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
repositoryUrl: "git@github.com/coreweave/ceph_exporter.git"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
      - type: "feature"
        release: "minor"
      - type: "update"
        release: "minor"
      - type: "refactor"
        release: "patch"
      - type: "bugfix"
        release: "patch"
      - type: "docs"
        release: "patch"
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
        - "BREAKING"
        - "BREAKS"
publish:
  - path: "@semantic-release/github"
